
package tela;

import classes.game1;


public class Splash extends javax.swing.JFrame {

    /**
     * Creates new form Splash
     */
    public Splash() {
        initComponents();
        
       
    }
        
           public void ledados (game1 aux){
            jLnome.setText(aux.getNome());
            
        
        
   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLultimaJogada = new javax.swing.JLabel();
        jLultima = new javax.swing.JLabel();
        jLmaior = new javax.swing.JLabel();
        jLnome = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(650, 560));
        setMinimumSize(new java.awt.Dimension(650, 560));
        setPreferredSize(new java.awt.Dimension(650, 560));
        getContentPane().setLayout(null);

        jLultimaJogada.setForeground(new java.awt.Color(255, 255, 255));
        jLultimaJogada.setText("jLabel4");
        getContentPane().add(jLultimaJogada);
        jLultimaJogada.setBounds(510, 450, 49, 40);

        jLultima.setForeground(new java.awt.Color(255, 255, 255));
        jLultima.setText("jLabel3");
        getContentPane().add(jLultima);
        jLultima.setBounds(350, 440, 49, 60);

        jLmaior.setForeground(new java.awt.Color(255, 255, 255));
        jLmaior.setText("jLabel2");
        getContentPane().add(jLmaior);
        jLmaior.setBounds(180, 450, 49, 40);

        jLnome.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLnome.setForeground(new java.awt.Color(255, 255, 255));
        jLnome.setText("jLabel2");
        getContentPane().add(jLnome);
        jLnome.setBounds(130, 30, 150, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Group 11.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 650, 550);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(50, 220, 120, 130);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         video obj = new video();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Splash().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLmaior;
    private javax.swing.JLabel jLnome;
    private javax.swing.JLabel jLultima;
    private javax.swing.JLabel jLultimaJogada;
    // End of variables declaration//GEN-END:variables

}
